/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scrollPaymasterSol from "./ScrollPaymaster.sol";
export type { scrollPaymasterSol };
export type { BasePaymasterCustom } from "./BasePaymasterCustom";
export type { SolvingPaymaster } from "./SolvingPaymaster";
export type { TokenPaymasterWithPYTH } from "./TokenPaymasterWithPYTH";
