/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOAppReducer,
  IOAppReducerInterface,
} from "../../../../../../@layerzerolabs/oapp-evm/contracts/oapp/interfaces/IOAppReducer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_cmd",
        type: "bytes",
      },
      {
        internalType: "bytes[]",
        name: "_responses",
        type: "bytes[]",
      },
    ],
    name: "lzReduce",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOAppReducer__factory {
  static readonly abi = _abi;
  static createInterface(): IOAppReducerInterface {
    return new Interface(_abi) as IOAppReducerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOAppReducer {
    return new Contract(address, _abi, runner) as unknown as IOAppReducer;
  }
}
